// Generated by the FlutterFire CLI.
import 'dart:io' show Platform;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isIOS) return ios;
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyFAKE00000000000000000000000000000',
    appId: '1:123456789012:android:0000000000000000000000',
    messagingSenderId: '123456789012',
    projectId: 'acme-orders-demo',
    storageBucket: 'acme-orders-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyFAKE11111111111111111111111111111',
    appId: '1:123456789012:ios:1111111111111111111111',
    messagingSenderId: '123456789012',
    projectId: 'acme-orders-demo',
    storageBucket: 'acme-orders-demo.appspot.com',
    iosBundleId: 'com.acme.orders',
  );
}
